import subprocess
import sys
import unittest
from pathlib import Path
from unittest import mock

from tests.python.support.paths import add_repo_path, repo_path

add_repo_path("skills/dxf/scripts")

from artifact import cli as artifact


class DxfArtifactCliTests(unittest.TestCase):
    """The CLI that closes the imported-DXF gap.

    Before this existed, `scripts/gen` was the skill's only entry point and it runs
    gen_dxf() generators — so an imported `.dxf` had no CLI at all, even though the
    viewer had been building its package on demand the whole time. These tests pin the
    part that made it a gap: that an imported drawing is accepted as a target.
    """

    def test_requires_a_target(self) -> None:
        with self.assertRaises(SystemExit) as cm:
            artifact.main([])
        self.assertEqual(2, cm.exception.code)

    def test_accepts_an_imported_dxf(self) -> None:
        with mock.patch.object(artifact, "build_dxf_artifact", return_value={"ok": True}) as build:
            self.assertEqual(0, artifact.main(["drawings/imported.dxf"]))

        self.assertEqual(Path("drawings/imported.dxf"), build.call_args.kwargs["source_path"])
        self.assertIsNone(build.call_args.kwargs["export"])
        self.assertFalse(build.call_args.kwargs["force"])

    def test_accepts_a_generator_source(self) -> None:
        with mock.patch.object(artifact, "build_dxf_artifact", return_value={"ok": True}) as build:
            self.assertEqual(0, artifact.main(["drawings/part.dxf.py"]))

        self.assertEqual(Path("drawings/part.dxf.py"), build.call_args.kwargs["source_path"])

    def test_a_generator_named_dxf_py_is_not_read_as_an_imported_drawing(self) -> None:
        # `part.dxf.py` ends in BOTH ".py" and — by naive suffix matching on the stem —
        # looks DXF-ish. The builder decides imported-vs-generated by the real suffix, so
        # the CLI must hand it the path unchanged rather than pre-classifying it.
        with mock.patch.object(artifact, "build_dxf_artifact", return_value={"ok": True}) as build:
            artifact.main(["drawings/part.dxf.py"])

        self.assertTrue(str(build.call_args.kwargs["source_path"]).endswith(".dxf.py"))

    def test_rejects_an_unrelated_suffix(self) -> None:
        with self.assertRaises(SystemExit) as cm:
            artifact.main(["drawings/part.step"])
        self.assertEqual(2, cm.exception.code)

    def test_passes_write_and_force(self) -> None:
        with mock.patch.object(artifact, "build_dxf_artifact", return_value={"ok": True}) as build:
            artifact.main(["drawings/imported.dxf", "--write", "out/copy.dxf", "--force"])

        self.assertEqual(Path("out/copy.dxf"), build.call_args.kwargs["export"])
        self.assertTrue(build.call_args.kwargs["force"])

    def test_scripts_artifact_directory_invokes_cli(self) -> None:
        skill_root = repo_path("skills/dxf")
        result = subprocess.run(
            [sys.executable, "scripts/artifact", "--help"],
            cwd=skill_root,
            check=False,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
        )
        self.assertEqual("", result.stderr)
        self.assertEqual(0, result.returncode)
        self.assertIn("usage: scripts/artifact", result.stdout)

    def test_cli_import_does_not_import_heavy_cad_modules(self) -> None:
        # Same contract scripts/gen holds: importing the CLI must not drag in OCP or the
        # STEP scene. A drawing build needs ezdxf and a Node child, nothing from the
        # solid-modelling stack.
        skill_root = repo_path("skills/dxf")
        code = (
            "import sys; sys.path.insert(0, 'scripts'); import artifact.cli; "
            "print('OCP.OCP' in sys.modules); "
            "print('irincad._internal.step_scene' in sys.modules)"
        )
        result = subprocess.run(
            [sys.executable, "-c", code],
            cwd=skill_root,
            check=False,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
        )
        self.assertEqual("", result.stderr)
        self.assertEqual(0, result.returncode)
        self.assertEqual(["False", "False"], result.stdout.strip().splitlines())


if __name__ == "__main__":
    unittest.main()
