"""Does each task actually reject a wrong answer?

`verify` proves a task is satisfiable: its reference passes it. That is
necessary and it is only half the question. A task whose assertions are too
loose passes things it should not, and verification cannot see that, because the
reference passes either way.

This asks the other half. Every task is given a deliberately wrong artifact and
must fail it. A task that passes is **vacuous**: it describes a requirement in
its prompt and checks something weaker, so an agent can satisfy it without doing
the work.

That is not a hypothetical failure mode. The vee block task asked for a 90
degree groove and asserted size, bounds, part count and the absence of holes,
every one of which a plain cube satisfies. A stand-in agent returned exactly a
plain cube and passed. Nothing in the corpus noticed until an accident found it.

The wrong answer used here is a **plain box of the reference's own bounding
size**. It is the most charitable wrong answer there is: right overall
dimensions, right position, one sound solid, no features. Any task that cannot
tell that from the real part is checking extents and calling them a
requirement.

Mutations that scale or perturb would find weaker tolerances too, and are worth
adding. This one is first because it is the cheapest to build, needs no CAD
kernel to generate, and finds the failure that actually occurred.
"""

from __future__ import annotations

import tempfile
from dataclasses import dataclass
from pathlib import Path
from typing import Callable, Sequence

from irineval import EvalError, InspectRunner, SpecResult, evaluate, measured_facts

from irinbench.corpus import KIND_TASK, Corpus, CorpusError

#: A sound solid with the right overall size and nothing else. Deliberately the
#: most charitable wrong answer: anything a task cannot reject here, it is not
#: really asking for.
_NULL_MODEL = '''"""A plain box with the reference's bounding size, and no features.

Generated by `irinbench probe`. If a task passes this, the task is checking
extents rather than the requirement its prompt states.
"""

from build123d import Align, Box, BuildPart

LENGTH = {x!r}
WIDTH = {y!r}
HEIGHT = {z!r}
ORIGIN = ({ox!r}, {oy!r}, {oz!r})


def gen_step():
    with BuildPart() as part:
        Box(LENGTH, WIDTH, HEIGHT, align=(Align.MIN, Align.MIN, Align.MIN))
    solid = part.part.translate(ORIGIN)
    solid.label = "null_model"
    return solid
'''


@dataclass(frozen=True)
class ProbeResult:
    """One task, given a wrong answer."""

    spec_id: str
    rejected: bool
    result: SpecResult | None
    error: str = ""

    @property
    def vacuous(self) -> bool:
        """Passed a plain box, so it is not checking what its prompt says."""
        return self.result is not None and not self.rejected

    def summary_line(self) -> str:
        if self.error:
            return f"SKIP  {self.spec_id}  ({self.error})"
        if self.rejected:
            assert self.result is not None
            failed = ", ".join(sorted({a.kind for a in self.result.failures()}))
            return f"ok    {self.spec_id}  rejected by {failed}"
        return f"WEAK  {self.spec_id}  a plain box passes this task"


@dataclass
class ProbeReport:
    results: tuple[ProbeResult, ...]

    @property
    def vacuous(self) -> tuple[ProbeResult, ...]:
        return tuple(r for r in self.results if r.vacuous)

    @property
    def skipped(self) -> tuple[ProbeResult, ...]:
        return tuple(r for r in self.results if r.error)

    @property
    def ok(self) -> bool:
        return not self.vacuous


def _null_model_source(facts: dict) -> str:
    size = facts["size"]
    bounds = facts["bounds"]["min"]
    return _NULL_MODEL.format(
        x=round(float(size[0]), 6),
        y=round(float(size[1]), 6),
        z=round(float(size[2]), 6),
        ox=round(float(bounds[0]), 6),
        oy=round(float(bounds[1]), 6),
        oz=round(float(bounds[2]), 6),
    )


def probe_corpus(
    corpus: Corpus,
    runner_for: Callable[[Path], InspectRunner],
    reference_runner: InspectRunner,
    *,
    only: Sequence[str] | None = None,
    on_result: Callable[[ProbeResult], None] | None = None,
) -> ProbeReport:
    """Give every task a plain box and record which ones fail to reject it.

    ``reference_runner`` measures the real part, to size the box. ``runner_for``
    builds a runner rooted at the throwaway directory the box is written into,
    because the CAD CLI resolves targets against its own working directory.
    """
    if corpus.kind != KIND_TASK:
        raise CorpusError(
            f"probing applies to a task corpus, not {corpus.kind!r}. A regression "
            "corpus records what a model measures, so a wrong answer is not a "
            "meaningful question to ask of it."
        )

    wanted = set(only) if only else None
    results: list[ProbeResult] = []

    for spec in sorted(corpus.specs, key=lambda s: s.id):
        if wanted is not None and spec.id not in wanted:
            continue

        reference = corpus.references.get(spec.id)
        if not reference:
            results.append(ProbeResult(spec.id, False, None, "no reference to size a box from"))
            if on_result:
                on_result(results[-1])
            continue

        try:
            facts = measured_facts(reference_runner, reference)
        except EvalError as exc:
            results.append(ProbeResult(spec.id, False, None, str(exc)[:80]))
            if on_result:
                on_result(results[-1])
            continue

        with tempfile.TemporaryDirectory(prefix="irin-probe-") as tmp:
            directory = Path(tmp)
            (directory / f"{spec.id}.step.py").write_text(
                _null_model_source(facts), encoding="utf-8"
            )
            runner = runner_for(directory)
            try:
                result = evaluate(spec, f"{spec.id}.step.py", runner)
            finally:
                close = getattr(runner, "close", None)
                if callable(close):
                    close()

        probe = ProbeResult(spec.id, rejected=not result.ok, result=result)
        results.append(probe)
        if on_result:
            on_result(probe)

    return ProbeReport(tuple(results))


def format_probe(report: ProbeReport) -> str:
    lines = ["IRIN task probe: does each task reject a plain box?", ""]
    checked = [r for r in report.results if not r.error]
    rejected = [r for r in checked if r.rejected]

    lines.append(f"  rejected  {len(rejected)} / {len(checked)}")

    if report.skipped:
        lines.append(f"  skipped   {len(report.skipped)}")

    if report.vacuous:
        lines.append("")
        lines.append("  these tasks are satisfied by a plain box of the right size,")
        lines.append("  so they check extents rather than what their prompt asks for:")
        lines.append("")
        for r in report.vacuous:
            lines.append(f"    {r.spec_id}")
        lines.append("")
        lines.append("  Add an assertion that measures the feature the prompt describes.")
        lines.append("  `volume` catches material added or removed; the feature counts")
        lines.append("  catch holes, bosses, blends and patterns.")
    else:
        lines.append("")
        lines.append("  every task rejects it")

    if report.skipped:
        lines.append("")
        lines.append("not probed:")
        for r in report.skipped:
            lines.append(f"  {r.spec_id}: {r.error}")

    return "\n".join(lines)
